export const books = [
  "Orgulho e Preconceito",
  "1984",
  "Dom Quixote de la Mancha",
  "O Pequeno Príncipe",
  "Dom Casmurro",
  "O Bandolim do Capitão Corelli",
  "O Conde de Monte Cristo",
  "Um Estudo em Vermelho",
  "O Processo",
  "Cem Anos de Solidão",
  "O Coração das Trevas",
  "Eu, Robô",
  "O Senhor dos Anéis",
  "Guerra e Paz",
  "Grande Sertão: Veredas",
  "O Retrato de Dorian Gray",
  "A Redoma de Vidro",
  "A Hora da Estrela",
  "Ensaio Sobre a Cegueira",
  "Maurice",
  "Por quem os Sinos Dobram",
  "Hamlet",
  "Morte em Veneza",
  "Em Busca do Tempo Perdido",
];
